// Copyright 2026 The openusd-fabric authors / V-Sekai contributors.
// SPDX-License-Identifier: Apache-2.0 OR MPL-2.0
//
// VRM 1.0 humanoid bone name list. Mirrored from
// openusd-fabric/maps/humanoid_bones_map.json (vrm1 column).
//
// **Drift risk** — CHI-254's `native_decide` byte-pin between the
// Lean source and the JSON is NOT enforced today (only pytest checks
// the JSON output). If the Lean spec changes, the JSON may not
// re-emit before this list is regenerated. The map should be
// considered the contract; this list mirrors it.
//
// Regeneration recipe (manual until CHI-254 lands the byte-pin):
//   1. cd openusd-fabric/lean && lake build && lake exe emit_artifacts
//   2. Verify openusd-fabric/maps/humanoid_bones_map.json updated
//   3. Re-extract vrm1 column into the array below
// A future cycle should make this generated by a Lake step that emits
// a C++ header alongside the JSON, closing the loop properly.

#include "idtx_core/internal/vrm_humanoid_bones.h"

#include <cstring>

namespace idtx::core::vrm {

static const char* const kHumanoidBoneNames[] = {
    "hips", "spine", "chest", "upperChest",
    "neck", "head", "leftEye", "rightEye", "jaw",
    "leftUpperLeg", "leftLowerLeg", "leftFoot", "leftToes",
    "rightUpperLeg", "rightLowerLeg", "rightFoot", "rightToes",
    "leftShoulder", "leftUpperArm", "leftLowerArm", "leftHand",
    "rightShoulder", "rightUpperArm", "rightLowerArm", "rightHand",
    "leftThumbMetacarpal", "leftThumbProximal", "leftThumbDistal",
    "leftIndexProximal", "leftIndexIntermediate", "leftIndexDistal",
    "leftMiddleProximal", "leftMiddleIntermediate", "leftMiddleDistal",
    "leftRingProximal", "leftRingIntermediate", "leftRingDistal",
    "leftLittleProximal", "leftLittleIntermediate", "leftLittleDistal",
    "rightThumbMetacarpal", "rightThumbProximal", "rightThumbDistal",
    "rightIndexProximal", "rightIndexIntermediate", "rightIndexDistal",
    "rightMiddleProximal", "rightMiddleIntermediate", "rightMiddleDistal",
    "rightRingProximal", "rightRingIntermediate", "rightRingDistal",
    "rightLittleProximal", "rightLittleIntermediate", "rightLittleDistal",
};
static constexpr size_t kHumanoidBoneCount =
    sizeof(kHumanoidBoneNames) / sizeof(kHumanoidBoneNames[0]);

bool is_humanoid_bone(const char* name)
{
    if (name == nullptr) return false;
    for (size_t i = 0; i < kHumanoidBoneCount; ++i) {
        if (std::strcmp(kHumanoidBoneNames[i], name) == 0) return true;
    }
    return false;
}

namespace {
    // Canonicalise: lowercase ASCII, strip non-alphanumeric. Caller
    // owns the buffer; returns the count written.
    size_t canonicalize_lower(const char* in, char* out, size_t cap) {
        size_t n = 0;
        if (in == nullptr) { out[0] = '\0'; return 0; }
        for (size_t i = 0; in[i] && n + 1 < cap; ++i) {
            char c = in[i];
            if (c >= 'A' && c <= 'Z')      out[n++] = static_cast<char>(c + ('a' - 'A'));
            else if (c >= 'a' && c <= 'z') out[n++] = c;
            else if (c >= '0' && c <= '9') out[n++] = c;
            // skip _, ., -, /, etc.
        }
        out[n] = '\0';
        return n;
    }
}

const char* match_humanoid_bone(const char* name)
{
    if (name == nullptr) return nullptr;
    char input_canon[64];
    canonicalize_lower(name, input_canon, sizeof(input_canon));
    if (input_canon[0] == '\0') return nullptr;
    for (size_t i = 0; i < kHumanoidBoneCount; ++i) {
        char canon[64];
        canonicalize_lower(kHumanoidBoneNames[i], canon, sizeof(canon));
        if (std::strcmp(canon, input_canon) == 0) {
            return kHumanoidBoneNames[i];
        }
    }
    return nullptr;
}

const char* const* humanoid_bone_names(size_t* out_count)
{
    if (out_count != nullptr) *out_count = kHumanoidBoneCount;
    return kHumanoidBoneNames;
}

}  // namespace idtx::core::vrm
